In [1]:
import pandas as pd
pd.__version__

'1.2.3'

In [2]:
df = pd.read_csv("samples/sample.csv")
df.head(6)

Year Industry_aggregation_NZSIOC  Industry_code_NZSIOC  \
0  2021                     Level 1                 99999   
1  2021                     Level 1                 99999   
2  2021                     Level 1                 99999   
3  2021                     Level 1                 99999   
4  2021                     Level 1                 99999   
5  2021                     Level 1                 99999   

  Industry_name_NZSIOC               Units Variable_code  \
0       All industries  Dollars (millions)           H01   
1       All industries  Dollars (millions)           H04   
2       All industries  Dollars (millions)           H05   
3       All industries  Dollars (millions)           H07   
4       All industries  Dollars (millions)           H08   
5       All industries  Dollars (millions)           H09   

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance   
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, dividends and donations  Financial performance   
3                             Non-operating income  Financial performance   
4                                Total expenditure  Financial performance   
5                           Interest and donations  Financial performance   

     Value                             Industry_code_ANZSIC06  
0  757,504  ANZSIC06 divisions A-S (excluding classes K633...  
1  674,890  ANZSIC06 divisions A-S (excluding classes K633...  
2   49,593  ANZSIC06 divisions A-S (excluding classes K633...  
3   33,020  ANZSIC06 divisions A-S (excluding classes K633...  
4  654,404  ANZSIC06 divisions A-S (excluding classes K633...  
5   26,138  ANZSIC06 divisions A-S (excluding classes K633...

In [4]:
df = pd.read_csv("samples/sample.csv")
df

Year Industry_aggregation_NZSIOC  Industry_code_NZSIOC  \
0  2021                     Level 1                 99999   
1  2021                     Level 1                 99999   
2  2021                     Level 1                 99999   
3  2021                     Level 1                 99999   
4  2021                     Level 1                 99999   
5  2021                     Level 1                 99999   
6  2021                     Level 1                 99999   
7  2021                     Level 1                 99999   

  Industry_name_NZSIOC               Units Variable_code  \
0       All industries  Dollars (millions)           H01   
1       All industries  Dollars (millions)           H04   
2       All industries  Dollars (millions)           H05   
3       All industries  Dollars (millions)           H07   
4       All industries  Dollars (millions)           H08   
5       All industries  Dollars (millions)           H09   
6       All industries  Dollars (millions)           H10   
7       All industries  Dollars (millions)           H11   

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance   
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, dividends and donations  Financial performance   
3                             Non-operating income  Financial performance   
4                                Total expenditure  Financial performance   
5                           Interest and donations  Financial performance   
6                                   Indirect taxes  Financial performance   
7                                     Depreciation  Financial performance   

     Value                             Industry_code_ANZSIC06  
0  757,504  ANZSIC06 divisions A-S (excluding classes K633...  
1  674,890  ANZSIC06 divisions A-S (excluding classes K633...  
2   49,593  ANZSIC06 divisions A-S (excluding classes K633...  
3   33,020  ANZSIC06 divisions A-S (excluding classes K633...  
4  654,404  ANZSIC06 divisions A-S (excluding classes K633...  
5   26,138  ANZSIC06 divisions A-S (excluding classes K633...  
6    6,991  ANZSIC06 divisions A-S (excluding classes K633...  
7   27,801  ANZSIC06 divisions A-S (excluding classes K633...

In [3]:
df.shape

(8, 10)

In [10]:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_is_numpy_dev',
 '_lib',
 '_libs',
 '_np_version_under1p17',
 '_np_version_under1p18',
 '_testing'

In [2]:
import numpy as np
np.__version__

'1.19.2'

In [3]:
np.array([2,4,5,6])

array([2, 4, 5, 6])

In [11]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [9]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

**arthmetic opertaors**

In [6]:
a = np.array([2,4,5,6])
a+4

array([ 6,  8,  9, 10])

In [12]:
 np.array([2,4,5,6])+5


array([ 7,  9, 10, 11])

In [15]:
a*2

array([ 4,  8, 10, 12])

In [8]:
a/2

array([1. , 2. , 2.5, 3. ])

In [17]:
a//2

array([1, 2, 2, 3], dtype=int32)

**element wise**

In [18]:
b = np.array([1,2,1,3])
a+b

array([3, 6, 6, 9])

In [19]:
a*b

array([ 2,  8,  5, 18])

In [20]:
a/b

array([2., 2., 5., 2.])

In [21]:
a//b

array([2, 2, 5, 2], dtype=int32)

**stack**

In [14]:
a


array([2, 4, 5, 6])

In [15]:
b

array([1. , 2. , 2.5, 3. ])

In [10]:

np.hstack([a,b])

array([2. , 4. , 5. , 6. , 1. , 2. , 2.5, 3. ])

In [23]:
np.vstack([a,b])

array([[2, 4, 5, 6],
       [1, 2, 1, 3]])

In [24]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [25]:
np.ones(3)

array([1., 1., 1.])

In [28]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(5,100,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [31]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [4]:
df.shape

(8, 10)

In [5]:
df.columns

Index(['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC',
       'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name',
       'Variable_category', 'Value', 'Industry_code_ANZSIC06'],
      dtype='object')

In [6]:
no_of_columns = df.shape[1]

In [ ]:
df.head(6)

In [14]:
df.loc[:,'Year']

0    2021
1    2021
2    2021
3    2021
4    2021
5    2021
6    2021
7    2021
Name: Year, dtype: int64

In [18]:
df.iloc[:,0:3]

Year Industry_aggregation_NZSIOC  Industry_code_NZSIOC
0  2021                     Level 1                 99999
1  2021                     Level 1                 99999
2  2021                     Level 1                 99999
3  2021                     Level 1                 99999
4  2021                     Level 1                 99999
5  2021                     Level 1                 99999
6  2021                     Level 1                 99999
7  2021                     Level 1                 99999

In [22]:
df.loc[:,'Industry_code_NZSIOC':]
["row"+str(i) for i in range(df.shape[0])]

['row0', 'row1', 'row2', 'row3', 'row4', 'row5', 'row6', 'row7']

In [25]:
df.index =["row"+str(i) for i in range(df.shape[0])]

In [ ]:
df

In [29]:
df.loc["row0":"row4"]
df.iloc[0:4]

Year Industry_aggregation_NZSIOC  Industry_code_NZSIOC  \
row0  2021                     Level 1                 99999   
row1  2021                     Level 1                 99999   
row2  2021                     Level 1                 99999   
row3  2021                     Level 1                 99999   

     Industry_name_NZSIOC               Units Variable_code  \
row0       All industries  Dollars (millions)           H01   
row1       All industries  Dollars (millions)           H04   
row2       All industries  Dollars (millions)           H05   
row3       All industries  Dollars (millions)           H07   

                                        Variable_name      Variable_category  \
row0                                     Total income  Financial performance   
row1  Sales, government funding, grants and subsidies  Financial performance   
row2                Interest, dividends and donations  Financial performance   
row3                             Non-operating income  Financial performance   

        Value                             Industry_code_ANZSIC06  
row0  757,504  ANZSIC06 divisions A-S (excluding classes K633...  
row1  674,890  ANZSIC06 divisions A-S (excluding classes K633...  
row2   49,593  ANZSIC06 divisions A-S (excluding classes K633...  
row3   33,020  ANZSIC06 divisions A-S (excluding classes K633...

In [31]:
df.Year.max()
#df['Year']


2021

In [32]:
df.describe()

Year  Industry_code_NZSIOC
count     8.0                   8.0
mean   2021.0               99999.0
std       0.0                   0.0
min    2021.0               99999.0
25%    2021.0               99999.0
50%    2021.0               99999.0
75%    2021.0               99999.0
max    2021.0               99999.0

In [33]:
df.dtypes

Year                            int64
Industry_aggregation_NZSIOC    object
Industry_code_NZSIOC            int64
Industry_name_NZSIOC           object
Units                          object
Variable_code                  object
Variable_name                  object
Variable_category              object
Value                          object
Industry_code_ANZSIC06         object
dtype: object

In [37]:
df.Units.unique()

array(['Dollars (millions)'], dtype=object)